Distance finding
RoboticsTeam4904/2017-Vision pull request #9
Opened 2017-02-11 20:22 UTC by oshlern

This code finds distance and angle to goal and publishes it to network tables. It is necessary for running with robot code. It has been tested and works. While it may still be inaccurate sometimes, it's definitely better than master. Additionally, it has the unused features of calculating the exact x and y displacements of the robot as well as it's absolute direction. New-distance is integrated with our 3 mains, and Printing has been modified to make readability with distance easier.

2017-02-11 21:50 UTC, c0d3rman submitted a review, later dismissed

2017-02-11 21:50 UTC, c0d3rman commented on PiMain.py
> +		isVisible, angleToGoal, distance = findSpike(targets)
Remove trailing whitespace

2017-02-11 21:50 UTC, c0d3rman commented on SpikeFinding.py
> +	# print squared, "not negative?" #SHOULDN"T BE NEGATIVE IF CAMERA MOUNTED PROPERLY AND CONSTANTS CORRECTLY LABELED
Remove

2017-02-11 21:50 UTC, c0d3rman commented on SpikeFinding.py
> +# def widthFromData(d1, d2, pxlsBetween):
Remove all commented out unused code

2017-02-11 21:50 UTC, c0d3rman commented on WebCam.py
> +	print resolution
Why is this necessary in `master`?

2017-02-11 21:50 UTC, c0d3rman commented on WebCamMain.py
> +				# print "The networktables are mean to us"
Remove

2017-02-11 21:50 UTC, c0d3rman commented on WebCamMain.py
> +		#cv2.waitKey(500)
Remove

2017-02-12 00:27 UTC, oshlern commented
Tested degrees to goal, and it was accurate

2017-02-12 22:18 UTC, CaseyManning requested changes
Seems Good

2017-02-12 22:18 UTC, CaseyManning commented on SpikeFinding.py
> +		print "no contours"
Delete or move to Printing.py?

2017-02-12 22:18 UTC, CaseyManning commented on SpikeFinding.py
> +	print np.degrees(np.multiply(config.degPerPxl[0], np.subtract(np.true_divide(config.resolution[0], 2), 0)))
Osher wants to put this in Printing.py instead.

2017-02-12 22:18 UTC, CaseyManning commented on SpikeFinding.py
> +		x1,y1,w1,h1 = cv2.boundingRect(contours[0])
minarearect?

2017-02-12 22:18 UTC, CaseyManning commented on SpikeFinding.py
> +		x1,y1,w1,h1 = cv2.boundingRect(contours[0])
-Osher

2017-02-12 22:30 UTC, CaseyManning approved these changes

2017-02-12 22:31 UTC, merged